@host = http://localhost:5139

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "derick",
    "lastName": "gagnon",
    "email": "derick.gag46@hotmail.com",
    "password": "1234"
}